# Generated by Django 4.1 on 2022-08-23 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0002_receita_pessoa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receita',
            name='pessoa',
        ),
    ]
